#!/bin/bash
#
#  gaeliumd The gaelium core server.
#
#
# chkconfig: 345 80 20
# description: gaeliumd
# processname: gaeliumd
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/gaeliumd, see below
if [ -f /etc/sysconfig/gaeliumd ]; then
        . /etc/sysconfig/gaeliumd
fi

RETVAL=0

prog=gaeliumd
# you can override the lockfile via GAELIUMD_LOCKFILE in /etc/sysconfig/gaeliumd
lockfile=${GAELIUMD_LOCKFILE-/var/lock/subsys/gaeliumd}

# gaeliumd defaults to /usr/bin/gaeliumd, override with GAELIUMD_BIN
gaeliumd=${GAELIUMD_BIN-/usr/bin/gaeliumd}

# gaeliumd opts default to -disablewallet, override with GAELIUMD_OPTS
gaeliumd_opts=${GAELIUMD_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $gaeliumd $gaeliumd_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
