description "Gaelium Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env GAELIUMD_BIN="/usr/bin/gaeliumd"
env GAELIUMD_USER="gaelium"
env GAELIUMD_GROUP="gaelium"
env GAELIUMD_PIDDIR="/var/run/gaeliumd"
# upstart can't handle variables constructed with other variables
env GAELIUMD_PIDFILE="/var/run/gaeliumd/gaeliumd.pid"
env GAELIUMD_CONFIGFILE="/etc/gaelium/gaelium.conf"
env GAELIUMD_DATADIR="/var/lib/gaeliumd"

expect fork

respawn
respawn limit 5 120
kill timeout 60

pre-start script
    # this will catch non-existent config files
    # gaeliumd will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$GAELIUMD_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run gaeliumd."
        echo "The setting must appear in $GAELIUMD_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following "
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"Gaelium Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$GAELIUMD_PIDDIR"
    chmod 0755 "$GAELIUMD_PIDDIR"
    chown $GAELIUMD_USER:$GAELIUMD_GROUP "$GAELIUMD_PIDDIR"
    chown $GAELIUMD_USER:$GAELIUMD_GROUP "$GAELIUMD_CONFIGFILE"
    chmod 0660 "$GAELIUMD_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$GAELIUMD_PIDFILE" \
    --chuid $GAELIUMD_USER:$GAELIUMD_GROUP \
    --exec "$GAELIUMD_BIN" \
    -- \
    -pid="$GAELIUMD_PIDFILE" \
    -conf="$GAELIUMD_CONFIGFILE" \
    -datadir="$GAELIUMD_DATADIR" \
    -disablewallet \
    -daemon

